// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCl5uvo1xTazhQzSM8wqej2cpxX5XTGLE',
    appId: '1:863331444436:web:e7bd0e0ee733097ba27d41',
    messagingSenderId: '863331444436',
    projectId: 'authentication-app-bloc',
    authDomain: 'authentication-app-bloc.firebaseapp.com',
    storageBucket: 'authentication-app-bloc.appspot.com',
    measurementId: 'G-4WYP97WCJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5AUVg8PJAcizOALVbasX4_H-8VUQZum4',
    appId: '1:863331444436:android:3fca7ef893e622dda27d41',
    messagingSenderId: '863331444436',
    projectId: 'authentication-app-bloc',
    storageBucket: 'authentication-app-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjVBYutwcjAJBXD-yclXM5gD-Tob12kg',
    appId: '1:863331444436:ios:bf0529678c62ad00a27d41',
    messagingSenderId: '863331444436',
    projectId: 'authentication-app-bloc',
    storageBucket: 'authentication-app-bloc.appspot.com',
    iosBundleId: 'com.example.authenticationFlutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwjVBYutwcjAJBXD-yclXM5gD-Tob12kg',
    appId: '1:863331444436:ios:8c250b116fd1bd5ca27d41',
    messagingSenderId: '863331444436',
    projectId: 'authentication-app-bloc',
    storageBucket: 'authentication-app-bloc.appspot.com',
    iosBundleId: 'com.example.authenticationFlutterBloc.RunnerTests',
  );
}
